# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibonacci_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historydata',
            name='input_number',
            field=models.IntegerField(unique=True),
        ),
    ]
