# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibonacci_app', '0003_auto_20180404_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historydata',
            name='fibonacci_result',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
