# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibonacci_app', '0005_auto_20180404_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historydata',
            name='input_number',
            field=models.IntegerField(),
        ),
    ]
